# Generated by Django 3.1.3 on 2021-01-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like_post_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
