# Generated by Django 3.1.3 on 2021-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210106_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(blank=True, max_length=56, null=True),
        ),
    ]
