# Generated by Django 3.1.3 on 2021-01-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followed_by_count',
            new_name='followers_counter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='following_count',
            new_name='posts_counter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='posts_count',
            new_name='watched_counter',
        ),
    ]
